# NLLB language codes used by the translation adapter.
# The UI can use short codes; the backend maps them to NLLB codes.

LANGUAGE_CODES = {
    "ar": "arb_Arab",
    "en": "eng_Latn",
    "fr": "fra_Latn",
    "es": "spa_Latn",
    "de": "deu_Latn",
    "it": "ita_Latn",
    "pt": "por_Latn",
    "tr": "tur_Latn",
    "ur": "urd_Arab",
    "fa": "pes_Arab",
    "id": "ind_Latn",
    "ms": "zsm_Latn",
    "bn": "ben_Beng",
    "hi": "hin_Deva",
    "ta": "tam_Taml",
    "te": "tel_Telu",
    "ml": "mal_Mlym",
    "pa": "pan_Guru",
    "gu": "guj_Gujr",
    "mr": "mar_Deva",
    "ru": "rus_Cyrl",
    "uk": "ukr_Cyrl",
    "zh": "zho_Hans",
    "ja": "jpn_Jpan",
    "ko": "kor_Hang",
    "th": "tha_Thai",
    "vi": "vie_Latn",
    "nl": "nld_Latn",
    "pl": "pol_Latn",
    "sv": "swe_Latn",
    "el": "ell_Grek",
    "he": "heb_Hebr",
}
